### ISSUE TITLE
Bug Report: bad error handling on 403 request.

### ISSUE THREAD

**Issue by uo283928** [Arquisoft/wiq_en2b#121] opened 2024-03-12 17:29 UTC
Application crashes (cannot read undefined) when a 403 request is sent.
Steps done were:
1 Login 
2 Start a game
3 Close the game's tab
4 Reopen it.

![IMG_20240312_174835_224](https://github.com/Arquisoft/wiq_en2b/assets/113936619/7c731585-ca5e-4d7b-96eb-264d7a8f0217)

**Comment by jjgancfer** [comment] 2024-03-31 18:37
Both @gony02 and I cannot reproduce it. We have been touching how authentication works, so we probably have already unknowingly fixed it.

**Comment by jjgancfer** [comment] 2024-03-31 20:27
@uo283928 has confirmed the bug seems to be solved, so I'm closing the issue.

**Closed by jjgancfer** 2024-03-31 20:27 UTC
Labels: bug 🐛
