### ISSUE TITLE
Component libraries for React

### ISSUE THREAD

**Issue by gony02** [Arquisoft/wiq_en2b#16] opened 2024-02-06 13:39 UTC
I would like to discuss which React Component Library is to be used in the project. I suggest using one of these three: 
- [Tailwind CSS](https://tailwindcss.com/)
- [MUI](https://mui.com/)
- [Chakra UI](https://chakra-ui.com/)

### Tailwind CSS
Despite being very customizable and visually attractive, it has poor documentation. There are not so many predefined components.

### MUI
It has a lot of different components and a comprehensive documentation. Although customizable, modifying styles can be more complex compared to the other libraries.

### Chakra UI
Provides a consistent and elegant design. It is the only one which is specifically designed for React, it makes integration with application logic straightforward. Moreover, it has a good documentation.

**Comment by sergiorodriguezgarcia** [comment] 2024-02-06 15:55
After carefully reviewing the options, I believe that the choice of MUI is a solid one due to its wide range of components and extensive documentation, in addition to being the choice in the proposed model. However, I also recognize the advantages of Chakra UI, especially its React-specific approach and its seamless integration with application logic. I believe it would be beneficial to further explore Chakra UI and evaluate how it aligns with our specific requirements and preferences for this project.

**Comment by jjgancfer** [comment] 2024-02-07 09:24
I think Chakra UI would be a nice fit, but we would have to rewrite the code we currently have if we do make the switch. On the other hand, MUI is more component-based than Chakra (which from what I have seen is more layout-based), but seems also heavier. Regarding Tailwind, while I do think would be a great choice, the free documentation about it I have seen is not as great as Chakra's.

> and its seamless integration with application logic.

This part does not seem beneficial to us, since most application logic will likely be server-side.

**Comment by uo283928** [comment] 2024-02-07 10:25
I have not done a very concise research about the options and being my role focused on backend, my opinion should be considered with caution.
I believe Tailwind could give you some troubles due to its lack of documentation while also you would to create many components on your own. This is why I would discard it.
Regarding MUI and Chakra UI, as they are well documented, things should be smoother. I can not really decide on any of both, as I am unsure about how much easier will be Chakra over MUI as it was designed for React.

**Comment by gony02** [comment] 2024-02-07 10:35
I have been researching about this libraries, and among them, MUI and Chakra UI stand out for having extensive documentation. The availability of comprehensive documentation is a crucial factor when considering the adoption of a library. However, from my point of view, MUI has a slightly outdated interface, which is why I suggest using Chakra UI.

**Comment by jjgancfer** [comment] 2024-02-09 17:48
I have been working in `feat/webapp/top-bar` with Chakra UI from `1b1a91f450453ba27de1b0c79b0ee359d8e2593f` onwards. I think it's been a much cleaner result than the previous one that used MUI, though it's not as easier to make it responsive (even so, it can be done), so I guess we better stick to Chakra.

Closing issue.

**Closed by jjgancfer** 2024-02-09 17:48 UTC
Labels: frontend 👁️
